### ISSUE TITLE
Local Emulator Issues with firebase-functions 4.1.1 and firebase-admin 11.4.0

### ISSUE THREAD

**Issue by chenrico** [firebase/firebase-tools#5345]
### [REQUIRED] Environment info

**firebase-tools:**
11.18.0

**Platform:**
macOS

### [REQUIRED] Test case

I have two issues:

(1) firebase-functions library

I use Typescript for the project. When `firebase-functions` is upgrade to greater than 4.0.0, I got this error below. 
When I reverted back to 3.24.1, it's working okay. When I deploy to the live environment, it's also working okay.

src/utils/Functions.ts:13:36 - error TS2307: Cannot find module 'firebase-functions/lib/providers/https' or its corresponding type declarations.
13 import { FunctionsErrorCode } from "firebase-functions/lib/providers/https";

(2) firebase-admin library

Again it worked with library before 11.0.0. When I deploy to the live environment, it's also working okay.

The line of code that has issue is just this:

import * as admin from "firebase-admin";
admin.initializeApp();
admin.firestore().settings({ ignoreUndefinedProperties: true });

export const firebaseNull = admin.firestore.FieldValue.delete();

⚠  Non-default "firebase-admin" instance created!
   - This instance will *not* be mocked and will access production resources.
⚠  TypeError: Cannot read properties of undefined (reading 'delete')
    at Object.<anonymous> (/Users/ricochen/Library/Mobile Documents/com~apple~CloudDocs/ReslyPMSCF/functions/lib/utils/firebase.js:13:61)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/ricochen/Library/Mobile Documents/com~apple~CloudDocs/ReslyPMSCF/functions/lib/utils/index.js:12:22)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.
⚠  functions: Failed to initialize and load triggers. This shouldn't happen: Cannot read properties of undefined (reading 'delete')
⚠  Your function was killed because it raised an unhandled error.

### [REQUIRED] Steps to reproduce

Use firebase-functions 4.1.1 and firebase-admin 11.4.0 and run local emulator

### [REQUIRED] Expected behavior

The same code throw an error when the firebase functions and admin library is updated.

### [REQUIRED] Actual behavior

The same code throw an error when the firebase functions and admin library is updated.

**Comment by aalej** [comment]
Hi @chenrico, thanks for the information you provided. I tried replicating the issue you mentioned by copying your provided code snippet and upgrading the version of the `firebase-functions` to 4.1.1 and `firebase-admin` to 11.4.0, but I am unable to encounter any issues running the local emulator.

With that, I would like to ask if you would be able to provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), or a more detailed steps you took so that I can replicate the issue you encountered? Also, to isolate the cause, could you try removing this line of code `export const firebaseNull = admin.firestore.FieldValue.delete();`, and let me know if you would still encounter the issue after doing so?
