### PR TITLE
Loop the modules properties without prototype methods. Fixes #1687

### LINKED ISSUE #1687: functions:deploy mod.hasOwnProperty is not a function
### Environment info

**firebase-tools:** v7.4.0
**Platform:** Ubuntu 19.04

### Problem

Trying to deploy a function:
`firebase deploy --only functions:Plivo.CallHangup`
stops with an error:
`Error: mod.hasOwnProperty is not a function`

### Actual behavior

```
✔  functions: Finished running predeploy script.
[2019-10-03T02:48:03.774Z] > [functions] package.json contents: {
  "name": "@sudshare/functions",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "@firebase/app": "0.x",
    "@sendgrid/helpers": "^6.4.0",
    "@sendgrid/mail": "^6.4.0",
    "busboy": "^0.3.1",
    "cors": "^2.8.5",
    "firebase-admin": "^8.3.0",
    "firebase-functions": "^3.2.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.26",
    "plivo": "^4.1.3",
    "rxjs": "6.5.2",
    "sharp": "^0.23.0",
    "stripe": "~7.9.1",
    "tslib": "^1.9.0"
  },
  "devDependencies": {
    "@types/moment-timezone": "^0.5.12",
    "@types/stripe": "^6.32.4",
    "@firebase/app-types": "0.x",
    "firebase-functions-test": "^0.1.6"
  },
  "engines": {
    "node": "8"
  },
  "main": "bundles/sudshare-functions.umd.js",
  "module": "fesm5/sudshare-functions.js",
  "es2015": "fesm2015/sudshare-functions.js",
  "esm5": "esm5/sudshare-functions.js",
  "esm2015": "esm2015/sudshare-functions.js",
  "fesm5": "fesm5/sudshare-functions.js",
  "fesm2015": "fesm2015/sudshare-functions.js",
  "typings": "sudshare-functions.d.ts",
  "metadata": "sudshare-functions.metadata.json",
  "sideEffects": false
}
i  functions: ensuring necessary APIs are enabled...
[2019-10-03T02:48:03.776Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/sudsharetest/services/cloudfunctions.googleapis.com  
 
[2019-10-03T02:48:03.777Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/sudsharetest/services/runtimeconfig.googleapis.com  
 
[2019-10-03T02:48:04.814Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:04 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:04.949Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:04 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
✔  functions: all necessary APIs are enabled
[2019-10-03T02:48:04.950Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/sudsharetest/adminSdkConfig  
 
[2019-10-03T02:48:05.535Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:05 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
i  functions: preparing dist/functions directory for uploading...
[2019-10-03T02:48:05.537Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs  
 
[2019-10-03T02:48:06.539Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:06 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:06.541Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/plivo/variables  
 
[2019-10-03T02:48:06.541Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/sendgrid/variables  
 
[2019-10-03T02:48:06.542Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/stripe/variables  
 
[2019-10-03T02:48:06.542Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/admin/variables  
 
[2019-10-03T02:48:06.542Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/gcp/variables  
 
[2019-10-03T02:48:06.544Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/giftup/variables  
 
[2019-10-03T02:48:08.004Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:07 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:08.005Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/admin/variables/client_x509_cert_url  
 
[2019-10-03T02:48:08.006Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/admin/variables/private_key  
 
[2019-10-03T02:48:08.006Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/admin/variables/private_key_id  
 
[2019-10-03T02:48:08.006Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/admin/variables/client_email  
 
[2019-10-03T02:48:08.006Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/admin/variables/client_id  
 
[2019-10-03T02:48:08.070Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:07 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:08.071Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/gcp/variables/apikey  
 
[2019-10-03T02:48:08.073Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:07 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:08.073Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/sendgrid/variables/key  
 
[2019-10-03T02:48:08.152Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:07 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:08.152Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/plivo/variables/number  
 
[2019-10-03T02:48:08.399Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:07 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:08.399Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/stripe/variables/livekey  
 
[2019-10-03T02:48:08.401Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:07 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:08.401Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/giftup/variables/key  
 
[2019-10-03T02:48:08.402Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/sudsharetest/configs/giftup/variables/testmode  
 
[2019-10-03T02:48:09.321Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.334Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.337Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.338Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.340Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.345Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.476Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.478Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.539Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.565Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2019-10-03T02:48:09.824Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 Oct 2019 02:48:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked

Error: mod.hasOwnProperty is not a function
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by matheo**
### Description

This fixes optimizations/bundles without `Object.__proto__` not having the `hasOwnProperty` method and failing to be deployed because of that, as described in #1687 

This is a simple fix with no major stuff involved.

### CODE REVIEW

**Comment by samtstern** [comment]
The GitHub diff is a little wonky here but it looks like the only change is:

**Before**
```js
for (var funcName in mod) {
    if (mod.hasOwnProperty(funcName)) {
```

**After**
```js
for (var funcName of Object.keys(mod)) {
```

Looks fine to me but I'd like @abeisgoat or @mbleigh to double-check.

**Comment by matheo** [comment]
Indeed @samtstern, that's the simple change ;)

**Comment by matheo** [comment]
@bkendall Changelog updated!

File: src/extractTriggers.js [hunk 1]
```diff
@@ -5,28 +5,26 @@
...
+      }
 
-        var trigger = {};
-        for (var key in child.__trigger) {
-          if (child.__trigger.hasOwnProperty(key)) {
-            trigger[key] = child.__trigger[key];
-          }
+      var trigger = {};
+      for (var key in child.__trigger) {
+        if (child.__trigger.hasOwnProperty(key)) {
```
Comment (laurenzlong) [inline src/extractTriggers.js]: Is this use of `hasOwnProperty` not susceptible to the same issue?

**Comment by laurenzlong** [comment]
To ensure that functions deploys are still working, can you please run the integrate test script in https://github.com/firebase/firebase-tools/blob/master/scripts/test-functions-deploy.js, and copy and paste the output here?

File: src/extractTriggers.js (hunk 1 above)
Comment (matheo) [reply src/extractTriggers.js]: It is not susceptible because it's built within `firebase-functions` but I will change this loop too just because `for of` looks better ;)

**Comment by matheo** [comment]
@laurenzlong Seems that I haven't a proper `FIREBASE_CONFIG` or `GCLOUD_PROJECT` env var to test that script, but I successfully deployed my functions patching the library with this `for of`.

**Comment by matheo** [comment]
@bkendall it's sad that this got to wait to the next release.
