### PR TITLE
Remove fast-crc32c dependency

### LINKED ISSUE #3239: dyld: lazy symbol binding failed: Symbol not found: __Z18sse42_is_availablev with version 9.8.0
### [REQUIRED] Environment info

**firebase-tools:** 9.8.0

**Platform:** macOS (Apple M1)

**NodeJS:** 15.12.0

### [REQUIRED] Test case

Any Firebase Functions project

### [REQUIRED] Steps to reproduce

Run this command:
```bash
firebase deploy --only functions
```

### [REQUIRED] Expected behavior

I'd expect it to deploy my functions as normal. It works perfectly with version 9.7.0 and below, but 9.8.0 breaks it.

### [REQUIRED] Actual behavior

```
dyld: lazy symbol binding failed: Symbol not found: __Z18sse42_is_availablev
  Referenced from: /Users/palkerecsenyi/.nvm/versions/node/v15.12.0/lib/node_modules/firebase-tools/node_modules/sse4_crc32/build/Release/crc32c.node
  Expected in: flat namespace

dyld: Symbol not found: __Z18sse42_is_availablev
  Referenced from: /Users/palkerecsenyi/.nvm/versions/node/v15.12.0/lib/node_modules/firebase-tools/node_modules/sse4_crc32/build/Release/crc32c.node
  Expected in: flat namespace

zsh: abort      firebase deploy --only functions:<redacted>,functions:<redacted>
```

### LINKED ISSUE #3247: No CRC-32C implementation available error in 9.8.0
### [REQUIRED] Environment info

**firebase-tools:** 9.7.0

**Platform:** Vercel Serverless Functions (Linux)

### [REQUIRED] Test case

When you deploy a project to Vercel that lists `firebase-tools@9.8.0` as a dependency (even if its just a development dependency), the following error occurs at runtime:

```
2021-03-31T03:13:51.397Z	185d337e-6d34-461e-870f-d2888b290646	ERROR	Uncaught Exception 	
{
  "errorType":"Error",
  "errorMessage":"no CRC-32C implementation is available",
  "stack":[
    "Error: no CRC-32C implementation is available","
      at Object.calculate (/var/task/node_modules/fast-crc32c/loader.js:18:13)","
      at PassThrough.onData [as _transform] (/var/task/node_modules/hash-stream-validation/index.js:23:37)","
      at PassThrough.Transform._read (_stream_transform.js:191:10)","
      at PassThrough.Transform._write (_stream_transform.js:179:12)","
      at doWrite (_stream_writable.js:403:12)","
      at writeOrBuffer (_stream_writable.js:387:5)","
      at PassThrough.Writable.write (_stream_writable.js:318:11)","
      at PassThrough.ondata (_stream_readable.js:718:22)","
      at PassThrough.emit (events.js:314:20)","
      at addChunk (_stream_readable.js:297:12)"
  ]
}
Unknown application error occurred
```

### [REQUIRED] Steps to reproduce

1. Create a new Next.js app that uses `firebase-tools@9.8.0`.
2. Deploy that app to Vercel.
3. Try to call the app's API routes.
4. See error in Vercel logs.

### [REQUIRED] Expected behavior

There should be no error. While I don't actually expect you to try to create this error, I'm creating this issue just in case anyone else has a similar issue (and this issue will help them determine that the source of it is `firebase-tools@9.8.0` and not anything to do with Vercel). You might also have some good pointers for why this might be happening in their serverless runtime environment.

### [REQUIRED] Actual behavior

See the above error logs.

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #3247
Fixes #3239

The `fast-crc32c` native module required by the storage emulator has been causing problems with our Firepit builds as well as running the NPM module on ARM systems.

I searched for a suitable all-JS replacement but was not able to find one which seemed to be high quality. So instead I used Wikipedia and Stackoverflow to figure out how to implement the algorithm ourselves and remove the dependency entirely.

### Scenarios Tested

I lifted 100% of the test cases from the `fast-crc32c` library we previously depended on and ran them against this new implementation, they all pass.

### Sample Commands

N/A

### CODE REVIEW

**Review by bkendall — APPROVED** [review]
LGTM. Thanks for taking this on.

**Comment by Brooooooklyn** [comment]
Would you like to try https://github.com/napi-rs/node-rs/tree/main/packages/crc32 , which is faster and support more platform:

|                  | node12 | node14 | node16 |
| ---------------- | ------ | ------ | ------ |
| Windows x64      | ✓      | ✓      | ✓      |
| Windows x32      | ✓      | ✓      | ✓      |
| Windows arm64    | ✓      | ✓      | ✓      |
| macOS x64        | ✓      | ✓      | ✓      |
| macOS arm64      | ✓      | ✓      | ✓      |
| Linux x64 gnu    | ✓      | ✓      | ✓      |
| Linux x64 musl   | ✓      | ✓      | ✓      |
| Linux arm gnu    | ✓      | ✓      | ✓      |
| Linux arm64 gnu  | ✓      | ✓      | ✓      |
| Linux arm64 musl | ✓      | ✓      | ✓      |
| Android arm64    | ✓      | ✓      | ✓      |
| FreeBSD x64      | ✓      | ✓      | ✓      |
