### ISSUE TITLE
Function emulator don't work with firebase-admin 8.8.0

### ISSUE THREAD

**Issue by mdunisch** [firebase/firebase-tools#1853]
### [REQUIRED] Environment info

7.9.0

**Platform:**
MacOS

### [REQUIRED] Test case

Start Firebase Emulators

### [REQUIRED] Steps to reproduce

`firebase emulators:start --only functions`

### [REQUIRED] Expected behavior

Start the emulator. But it fails with with the latest firebase-admin. With 8.7.0 it works well.

### [REQUIRED] Actual behavior

⚠  Error: Cannot find module '@firebase/component'
Require stack:
- functions/node_modules/@firebase/database/dist/index.node.cjs.js
- functions/node_modules/firebase-admin/lib/firebase-namespace.js
- functions/node_modules/firebase-admin/lib/default-namespace.js
- functions/node_modules/firebase-admin/lib/index.js
- functions/node_modules/firebase-functions/lib/apps.js
- functions/node_modules/firebase-functions/lib/providers/database.js
- functions/node_modules/firebase-functions/lib/index.js
- /Users/m/.nvm/versions/node/v12.11.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (functions/node_modules/@firebase/database/dist/index.node.cjs.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
⚠  We were unable to load your functions code. (see above)

**Comment by samtstern** [comment]
@mdunisch could you show me some code that will help me reproduce this issue?  I tried a very basic function with `firebase-admin` version `8.8.0` (below) and did not get the crash you're seeing:

```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

exports.helloWorld = functions.https.onRequest((request, response) => {
 response.send("Hello from Firebase!");
});
```

**Comment by mdunisch** [comment]
thank you for your quick answer. We tried a complete reinstall of all npm-packages (without cache) and it works now!

**Comment by samtstern** [comment]
@mdunisch thanks for following up!
