### ISSUE TITLE
Jest is unable to resolve dependencies after upgrading to 10.1.0

### ISSUE THREAD

**Issue by amkoehler** [firebase/firebase-tools#4321]
### [REQUIRED] Environment info

**firebase-tools: 10.1.0**

**Platform: Windows, Ubuntu**

### [REQUIRED] Test case

After upgrading our `firebase-tools` library from 9 to the latest (10.3.1), our unit tests started failing with the following error:

```
    Cannot find module 'cli-color' from '../../node_modules/firebase-tools/lib/index.js'

    Require stack:
      /home/alex/dev/layer/node_modules/firebase-tools/lib/index.js
      src/cleanupDeleted.ts
      test/cleanupDeleted.test.ts
```

To narrow it down, I tested every version in between `9.23.3` and `10.3.1`. My tests worked for `10.0.0` and `10.0.1` but failed at `10.1.0`. The `10.1.0` release contained some changes to dependency management with `npm-shrinkwrap.json`, so I'm wondering if that introduced an incompatibility with how jest resolves modules? 

When I install any `<10.3.1` version, I noticed my root `node_modules` contains dependencies for `firebase-tools`, such as `cli-color`, but when installing `10.3.1` those modules are no longer in my root `node_modules`. Is that expected behavior with the `10.3.1` changes?

### [REQUIRED] Steps to reproduce

1. Install `10.1.0+` of `firebase-tools` in a project that uses jest and imports `firebase-tools`
2. Write a test for a function that imports `firebase-tools`. As an example, we use `firebase-tools` to [recursively delete](https://firebase.google.com/docs/firestore/solutions/delete-collections) a firestore collection and have accompanying test cases.
3. Run the test

### [REQUIRED] Expected behavior

The dependencies of `firebase-tools` can be resolved when running unit tests with jest. I have not tried other test suites. 

### [REQUIRED] Actual behavior

I'm unable to run with the `--debug` flag, since the module resolution is failing when importing the `firebase-tools` library. I realize this is a unique use case since we're importing `firebase-tools` in a node script rather than using the CLI command, however we built this based on an [official example](https://firebase.google.com/docs/firestore/solutions/delete-collections) from firebase documentation.

**Comment by bkendall** [comment]
Thanks for the detail. Would it be possible to provide a minimal repro case for this? Since we don't use `jest`, I'm not sure what it looks like to implement a test with it w/ `firebase-tools`. An example repo (or gist) with a `package.json` and a `test.js` seems like it would be just enough to show the issue. Then we can take a look.

But in the same vein: since `jest` isn't something I'm super familiar with, if it's not something obvious we can fix in the package/repo, this question might be better suited for Stack Overflow or the [Firebase Community Slack](https://firebase.community)

**Comment by amkoehler** [comment]
Hey @bkendall, sure thing. Here's a repo I set up that demonstrates the bug: https://github.com/amkoehler/firebase-tools-v10-dep-bug  

My understanding of `node_modules` structure is beginner-level, at best, but I'll reiterate that I found it odd that v10 doesn't include its dependencies in my `node_modules` (such as `cli-color` and `commander`) but version 9 does. With version 10.1.0+ they are only found in `node_modules/firebase-tools/node_modules`.

**Comment by bkendall** [comment]
Thanks for the repro. This is really confusing. For whatever reason, the modules just aren't being found when it's being run with `jest`. I may not be able to address it this week (or in the short term), but I'll keep it in the back of my mind.

**Comment by amkoehler** [comment]
Ok, thanks for taking a look. Jest's module resolution is kind of a mess right now. As a workaround I can install each of the missing modules, which brings them into my `node_modules` where Jest can find them.

**Comment by amkoehler** [comment]
I found another workaround--and potentially a better solution--for recursive deletes. `firebase-admin` now provides a [way](https://googleapis.dev/nodejs/firestore/latest/Firestore.html#recursiveDelete) to recursively delete collections w/o needing to import `firebase-tools`. This makes our tests much easier to manage since `firebase-admin` is used everywhere.

**Comment by bkendall** [comment]
I'm going to close this as not planned since it's so old. Hopefully time has fixed this.
