### ISSUE TITLE
Error: Cannot find module 'node:process' since I upgraded to 11.0.1

### ISSUE THREAD

**Issue by julienlebren** [firebase/firebase-tools#4595]
### [REQUIRED] Environment info

**firebase-tools:** 11.0.1

**Platform:** macOS

### [REQUIRED] Test case

Since I upgraded to 11.0.1, I cannot launch any firebase feature.
For example, when typing `firebase functions:shell` or `firebase deploy`, this is the returned log:

### [REQUIRED] Steps to reproduce

I just require any Firebase feature, for example `firebase functions:shell` or `firebase deploy`.

### [REQUIRED] Expected behavior

It's just expected to work.

### [REQUIRED] Actual behavior

Currently it returns the following error:

```
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'node:process'
Require stack:
- /Users/julienlebren/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/node_modules/marked-terminal/index.cjs
- /Users/julienlebren/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/lib/bin/firebase.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/julienlebren/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/node_modules/marked-terminal/index.cjs:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/julienlebren/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/node_modules/marked-terminal/index.cjs',
    '/Users/julienlebren/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/lib/bin/firebase.js'
  ]
}
```

When rolling back to 10.9.2, everything works fine.

**Comment by Blidnight** [comment]
`Error: Cannot find module 'node:process'`

Try to update the nodejs version on your PC to a more recent version and it should solved the problem

**Comment by zenbakiak** [comment]
@Blidnight I'm using the current stable version, same error:

```
 firebase emulators:start --only hosting,functions,ui
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'node:process'
Require stack:
- /Users/zenbakiak/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/node_modules/marked-terminal/index.cjs
- /Users/zenbakiak/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/lib/bin/firebase.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/zenbakiak/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/node_modules/marked-terminal/index.cjs:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/zenbakiak/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/node_modules/marked-terminal/index.cjs',
    '/Users/zenbakiak/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/lib/bin/firebase.js'
  ]
}
❯ node -v
v15.14.0
❯ nvm ls
       v10.24.1
->     v15.14.0
         system
default -> node (-> v15.14.0)
```

**Comment by bkendall** [comment]
@julienlebren I see you're using `v15`, which is not a stable version of node. Upgrade to >= 16.2 and it should work for you. I'm not sure where or if in v15 [node: imports](https://nodejs.org/api/esm.html#node-imports) were added

**Comment by julienlebren** [comment]
Upgrade to node 16 solved the issue, thank you.

```
julienlebren@MacBook-Pro-de-Julien mcj % node -v
v15.14.0
julienlebren@MacBook-Pro-de-Julien mcj % nvm use 16
Now using node v16.13.2 (npm v8.1.2)
julienlebren@MacBook-Pro-de-Julien mcj % node -v   
v16.13.2
julienlebren@MacBook-Pro-de-Julien mcj % firebase functions:shell
⚠  functions: The following emulators are not running, calls to these services will affect production: firestore, database, pubsub, storage
firebase > 
```
