### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: __Z18sse42_is_availablev with version 9.8.0

### ISSUE THREAD

**Issue by palkerecsenyi** [firebase/firebase-tools#3239]
### [REQUIRED] Environment info

**firebase-tools:** 9.8.0

**Platform:** macOS (Apple M1)

**NodeJS:** 15.12.0

### [REQUIRED] Test case

Any Firebase Functions project

### [REQUIRED] Steps to reproduce

Run this command:
```bash
firebase deploy --only functions
```

### [REQUIRED] Expected behavior

I'd expect it to deploy my functions as normal. It works perfectly with version 9.7.0 and below, but 9.8.0 breaks it.

### [REQUIRED] Actual behavior

```
dyld: lazy symbol binding failed: Symbol not found: __Z18sse42_is_availablev
  Referenced from: /Users/palkerecsenyi/.nvm/versions/node/v15.12.0/lib/node_modules/firebase-tools/node_modules/sse4_crc32/build/Release/crc32c.node
  Expected in: flat namespace

dyld: Symbol not found: __Z18sse42_is_availablev
  Referenced from: /Users/palkerecsenyi/.nvm/versions/node/v15.12.0/lib/node_modules/firebase-tools/node_modules/sse4_crc32/build/Release/crc32c.node
  Expected in: flat namespace

zsh: abort      firebase deploy --only functions:<redacted>,functions:<redacted>
```

**Comment by tiny-dancer** [comment]
https://stackoverflow.com/questions/66816456/firebase-broken-on-m1-mac

> which firebase-tools do you have? had the same issue with 9.8.0 - downgrading to 9.7.0 made it work – RandomDude yesterday

**Comment by robinpdev** [comment]
Had this exact issue too, i guess firebase QA needs some waking up.

**Comment by tiny-dancer** [comment]
Some new equipment :)

**Comment by samtstern** [comment]
@robinpdev please be respectful when commenting here!

**Comment by robinpdev** [comment]
@samtstern Sorry if that offensive, still love firebase🔥

**Comment by samtstern** [comment]
@palkerecsenyi thanks for reporting this, we've had a few issues with M1 macs and especially with Node 15.  Unfortunately since we've all been working from home during the pandemic nobody on our team has been able to get a new laptop for work so we don't have good M1 test coverage and GitHub actions (where we do our CI testing) doesn't have ARM or M1 options.

I'll report this to some team members who may have bought their own M1 machines and see if they can reproduce it.

**Comment by miketrebilcock** [comment]
Looks like the addition of fast-crc32c within the emulators created the problem in 9.8.0. https://github.com/firebase/firebase-tools/compare/v9.7.0...v9.8.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by samtstern** [comment]
@miketrebilcock thanks for pointing that out!  I bet you're right.

**Comment by wiesson** [comment]
I'm not sure, but it looks like this package does compile natively https://github.com/napi-rs/node-rs/tree/main/packages/crc32 and could replace `fast-crc32c` 🤔

**Comment by bradleymackey** [comment]
Just a heads up that I'm also seeing this issue on `armv7l` on a Raspberry Pi.

**Comment by fernandolguevara** [comment]
can you release a version with this fix ? please?

**Comment by samtstern** [comment]
This is fixed in version `9.9.0`

**Comment by fernandolguevara** [comment]
@samtstern thanks!! =)
